const data = {
    products: [
        {
            _id: '1',
            name: 'Pleteni set za bebe',
            category: 'kompleti',
            image: 'images/product-1.jpg',
            price: '3700',
            brand: 'nepoznat',
            rating: '4.5',
            numReviews: '10',
            description: 'Pleteni kompletić za najmlađe. Kapa, rukavice, džemper i pantalonice od najkvalitetnije vune.',
        },
        {
            _id: '2',
            name: 'Mini bade mantil',
            category: 'ostalo',
            image: 'images/product-2.jpg',
            price: '2100',
            brand: 'nepoznat',
            rating: '4.1',
            numReviews: '13',
            description: 'Plišani bade-mantil da ušuškate svog mladunca.',
        },
        {
            _id: '3',
            name: 'IT benkica',
            category: 'benkice',
            image: 'images/product-3.jpg',
            price: '900',
            brand: 'nepoznat',
            rating: '3.8',
            numReviews: '7',
            description: 'Benkica za buduće programere!',
        },
        {
            _id: '4',
            name: 'Smeđe pantalone sa tregerima',
            category: 'pantalone',
            image: 'images/product-4.jpg',
            price: '1300',
            brand: 'nepoznat',
            rating: '4.5',
            numReviews: '18',
            description: 'Udobne i praktične, pletene smeđe pantalonice na tregere.',
        },
        {
            _id: '5',
            name: 'Benkica na tufne',
            category: 'benkice',
            image: 'images/product-5.jpg',
            price: '950',
            brand: 'nepoznat',
            rating: '4.6',
            numReviews: '20',
            description: 'Jednostavna ali efektna benkica na tufne.',
        },
        {
            _id: '6',
            name: 'Zelene pantalone sa tregerima',
            category: 'pantalone',
            image: 'images/product-6.jpg',
            price: '1300',
            brand: 'nepoznat',
            rating: '4.9',
            numReviews: '14',
            description: 'Pamučno zeleno odelce sa džepićem za cuclu.',
        },
        {
            _id: '7',
            name: 'Komplet za decaka',
            category: 'kompleti',
            image: 'images/product-7.jpg',
            price: '3300',
            brand: 'nepoznat',
            rating: '4.2',
            numReviews: '6',
            description: 'Košulja, duks i pantalonice za dečaka.',
        },
    ]
}

export default data;